const words = [
    { word: "apologize", translation: "להתנצל", definition: "to tell someone that you are sorry that you have done something wrong" },
    { word: "be responsible for", translation: "להיות אחראי ל-", definition: "to be in charge of or to take care of" },
    { word: "condition", translation: "מצב תנאים", definition: "The particular state that someone or something is in" },
    { word: "convince", translation: "לשכנע", definition: "to make somebody/yourself believe that something is true, or to persuade somebody" },
    { word: "doubt", translation: "ספק", definition: "a feeling of being not sure whether something is true or right" },
    { word: "encourage", translation: "לעודד", definition: "to give someone courage or confidence to do something" },
    { word: "even", translation: "אפילו", definition: "used to emphasize something that is unexpected or surprising" },
    { word: "fight", translation: "מאבק", definition: "a situation in which two people or groups hit or argue with each other" },
    { word: "hug", translation: "לחבק", definition: "to put your arms around someone and hold them tightly" },
    { word: "invent", translation: "להמציא", definition: "to make or design a new type of thing" },
    { word: "minister", translation: "שר", definition: "a politician who is in charge of a government department" },
    { word: "otherwise", translation: "אחרת", definition: "differently; in another way" },
    { word: "president", translation: "נשיא", definition: "the official leader of a country or company" },
    { word: "tax", translation: "מס", definition: "an amount of money paid to the government" },
    { word: "tell", translation: "לספר", definition: "to communicate information or a story" },
    { word: "terrible", translation: "נורא", definition: "extremely severe in a way that causes harm or damage" },
    { word: "truth", translation: "אמת", definition: "real facts" },
    { word: "twice", translation: "פעמיים", definition: "two times" },
    { word: "afford", translation: "להרשות לעצמו", definition: "to have enough money to buy or do something" },
    { word: "blame", translation: "להאשים", definition: "to say or think that someone is responsible for something bad" },
    { word: "enemy", translation: "אויב", definition: "someone who hates you and wants to harm you" },
    { word: "extremely", translation: "מאוד", definition: "to a very great degree" },
    { word: "hunger", translation: "רעב", definition: "lack of food for a long period of time" },
    { word: "lie", translation: "שקר", definition: "something that you say or write that you know is untrue" },
    { word: "make up", translation: "להמציא", definition: "to pretend that something is true to deceive someone" },
    { word: "upset", translation: "כועס נסער", definition: "unhappy and worried because something unpleasant happened" }
];
